### ISSUE TITLE
[Docs] ドキュメントを整備する

### ISSUE THREAD

**Issue by ensan-hcl** [ensan-hcl/AzooKeyKanaKanjiConverter#2]

**Comment by Kyome22** [comment]
パッとやった方が良さそうなこと
- Packageの指定方法
- Copy Bundle ResourcesにDictionaryディレクトリを指定することを書く
- 『azooKeyのかな漢字変換モジュールを切り出したライブラリです。』のazooKeyをリンクにする

**Comment by ensan-hcl** [comment]
ありがとうございます！少し手を入れました！！
